# Generated by Django 4.1.6 on 2023-02-15 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_accounts'),
        ('trees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantedtree',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.account'),
        ),
    ]
